# Generated by Django 4.1.5 on 2023-01-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_testimonial_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactprofile",
            name="message",
            field=models.TextField(default="DEFAULT VALUE", verbose_name="Message"),
        ),
    ]
