# Generated by Django 4.1.5 on 2023-01-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_contactprofile_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="cert",
            field=models.FileField(blank=True, null=True, upload_to="certs"),
        ),
    ]
