# Generated by Django 4.1.5 on 2023-01-13 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_certificate_options_certificate_body"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="certificate",
            options={
                "verbose_name": "Certificate",
                "verbose_name_plural": "Certificates",
            },
        ),
        migrations.RemoveField(
            model_name="certificate",
            name="body",
        ),
        migrations.RemoveField(
            model_name="certificate",
            name="cert",
        ),
    ]
